- id: '1685484926415'
  alias: Coming home
  description: ''
  trigger:
  - platform: state
    entity_id:
    - zone.home
    from: '0'
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.bedroom_bright
    metadata: {}
  mode: single
- id: '1685485971496'
  alias: Leaving home
  description: ''
  trigger:
  - platform: state
    entity_id:
    - zone.home
    to: '0'
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      area_id: bedroom
  mode: single
- id: '1685559409214'
  alias: Sunrise
  description: ''
  trigger:
  - platform: template
    value_template: '{% set x = states(''sensor.sm_a528b_next_alarm'') %} {% if x
      not in [''unavailable'', ''none'', ''unknown''] %}  {{ now() >= x | as_datetime
      | as_local - timedelta(minutes=30) }} {%else%} False {% endif %}'
  condition: []
  action:
  - parallel:
    - if:
      - condition: and
        conditions:
        - condition: not
          conditions:
          - condition: state
            entity_id: zone.home
            state: '0'
        - condition: state
          entity_id: light.chandelier_1
          state: 'off'
      then:
      - service: script.hue_gentle_sunrise
        data: {}
    - delay:
        hours: 0
        minutes: 30
        seconds: 0
        milliseconds: 0
  - service: notify.mobile_app_sm_a528b
    data:
      message: command_ringer_mode
      data:
        command: normal
  mode: single
- id: maciej_wifi_status
  alias: Maciej WiFi status
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.sm_a528b_wifi_connection
    to:
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ ''Whonnock'' in states(''sensor.sm_a528b_wifi_connection'')
          }}'
      sequence:
      - service: mqtt.publish
        data:
          topic: location/maciej_wifi
          payload: home
          retain: true
    default:
    - service: mqtt.publish
      data:
        topic: location/maciej_wifi
        payload: not_home
        retain: true
  initial_state: 'on'
- id: '1697492399303'
  alias: Aqara H1 Switch
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.aqara_wireless_remote_switch_h1_action
    attribute: action
    id: single_left
    to: single_left
  - platform: state
    entity_id:
    - sensor.aqara_wireless_remote_switch_h1_action
    attribute: action
    id: double_left
    to: double_left
  - platform: state
    entity_id:
    - sensor.aqara_wireless_remote_switch_h1_action
    attribute: action
    id: triple_left
    to: triple_left
  - platform: state
    entity_id:
    - sensor.aqara_wireless_remote_switch_h1_action
    attribute: action
    id: hold_left
    to: hold_left
  - platform: state
    entity_id:
    - sensor.aqara_wireless_remote_switch_h1_action
    attribute: action
    id: single_right
    to: single_right
  - platform: state
    entity_id:
    - sensor.aqara_wireless_remote_switch_h1_action
    attribute: action
    id: double_right
    to: double_right
  - platform: state
    entity_id:
    - sensor.aqara_wireless_remote_switch_h1_action
    attribute: action
    id: triple_right
    to: triple_right
  - platform: state
    entity_id:
    - sensor.aqara_wireless_remote_switch_h1_action
    attribute: action
    id: hold_right
    to: hold_right
  - platform: state
    entity_id:
    - sensor.aqara_wireless_remote_switch_h1_action
    attribute: action
    id: hold_both
    to: hold_both
  condition: []
  action:
  - parallel:
    - if:
      - condition: trigger
        id:
        - single_left
      then:
      - service: hue.activate_scene
        data: {}
        target:
          entity_id: scene.bedroom_relax
    - if:
      - condition: trigger
        id:
        - double_left
      then: []
    - if:
      - condition: trigger
        id:
        - triple_left
      then: []
    - if:
      - condition: trigger
        id:
        - hold_left
      then:
      - service: script.going_to_sleep
        data: {}
    - if:
      - condition: trigger
        id:
        - single_right
      then:
      - service: hue.activate_scene
        data: {}
        target:
          entity_id: scene.bedroom_bright
    - if:
      - condition: trigger
        id:
        - double_right
      then: []
    - if:
      - condition: trigger
        id:
        - triple_right
      then: []
    - if:
      - condition: trigger
        id:
        - hold_right
      then:
      - service: hue.activate_scene
        data: {}
        target:
          entity_id: scene.bedroom_concentrate
    - if:
      - condition: trigger
        id:
        - hold_both
      then:
      - service: light.turn_off
        data: {}
        target:
          entity_id: light.bedroom
  mode: single
- id: '1701205376723'
  alias: Window open notification
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.window_sensor_contact
    to: 'on'
    id: open
  - platform: state
    entity_id:
    - binary_sensor.window_sensor_contact
    to: 'off'
    id: closed
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - open
      sequence:
      - service: notify.mobile_app_sm_a528b
        data:
          message: Your window is currently open!
          title: Alert
          data:
            tag: window-open
            channel: alert
            sticky: true
            persistent: true
    - conditions:
      - condition: trigger
        id:
        - closed
      sequence:
      - service: notify.mobile_app_sm_a528b
        data:
          message: clear_notification
          data:
            tag: window-open
            channel: alert
            sticky: true
            persistent: true
  mode: single
- id: '1718126839606'
  alias: Door open notification
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.door_sensor_contact
    to: 'on'
    id: open
  - platform: state
    entity_id:
    - binary_sensor.door_sensor_contact
    to: 'off'
    id: closed
  condition:
  - condition: state
    entity_id: zone.home
    state: '0'
  action:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - open
      sequence:
      - parallel:
        - service: notify.mobile_app_sm_a528b
          data:
            message: Your door was opened while you were away!
            title: Alert
            data:
              tag: door-open
              channel: alert
              sticky: true
              persistent: true
        - service: hue.activate_scene
          target:
            entity_id: scene.bedroom_bright
          data: {}
    - conditions:
      - condition: trigger
        id:
        - closed
      sequence: []
  mode: single
