# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes/

# Text to speech
tts:
  - platform: google_translate

automation: !include yaml-configs/automations.yaml
script: !include yaml-configs/scripts.yaml
scene: !include yaml-configs/scenes.yaml
zone: !include yaml-configs/zones.yaml
sensor: !include yaml-configs/sensors.yaml
group: !include yaml-configs/groups.yaml
light: !include yaml-configs/lights.yaml
mqtt: !include yaml-configs/mqtt.yaml
