# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes/

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml #HA breaks hardlinks when editing automations and can't read a file that is a symlink, read readme
group: !include yaml-configs/groups.yaml
http: !include yaml-configs/http.yaml
light: !include yaml-configs/lights.yaml
mqtt: !include yaml-configs/mqtt.yaml
scene: !include yaml-configs/scenes.yaml
script: !include yaml-configs/scripts.yaml
#secret: !include yaml-configs/secrets.yaml
sensor: !include yaml-configs/sensors.yaml
zone: !include yaml-configs/zones.yaml
