- platform: time_date
  display_options:
    - "time"
    - "date"
    - "date_time"
    - "date_time_utc"
    - "date_time_iso"
    - "time_date"
    - "time_utc"
    - "beat"
- platform: template
  sensors:
    asus_zenbook_battery_charge_remaining_percentage_preserved:
      friendly_name: "Asus Zenbook battery charge remaining percentage preserved"
      icon_template: mdi:battery-90
      unit_of_measurement: "%"
      value_template: >-
        {% if  states('sensor.asus_zenbook_battery_charge_remaining_percentage') == "unavailable" %}
          {{ states('sensor.asus_zenbook_battery_charge_remaining_percentage_preserved') }}
        {% else %}
          {{ states('sensor.asus_zenbook_battery_charge_remaining_percentage') }}
        {% endif %}
